
<?php
    $title = $this->config->name;
    // if(isset($_meta['title']))
    //     $title = $_meta['title'] . ' - ' . $title;
?>
<div class="header header-fixed header-logo-center header-auto-show">
    <a href="/" class="header-title"><?= $title ?></a>
</div>

<div class="page-title page-title-fixed">
    <h1><?= $title ?></h1>
</div>
<div class="page-title-clear"></div>

<div class="page-content mt-n1">
    <div class="search-no-results disabled mt-4">
        <div class="card card-style">
            <div class="content">
                <h1>No Results</h1>
                <p>
                    Your search brought up no results. Try using a different keyword. Or try typying all
                    to see all items in the demo. These can be linked to anything you want.
                </p>
            </div>
        </div>
    </div>

    <div class="content mt-0 mb-n1">
        <div class="d-flex">
            <div class="align-self-center">
                <h1 class="mb-0 font-16">Destination at Bogor</h1>
            </div>
            <div class="ms-auto align-self-center">
                <a href="<?= $this->router->to('sitePostList', ['type' => 'destination '])?>" class="float-end font-12 font-400">See All</a>
            </div>
        </div>
    </div>

    <div class="splide single-slider slider-no-arrows visible-slider slider-no-dots" id="single-slider-1">
        <div class="splide__track">
            <div class="splide__list">`
                <?php foreach($destinations as $post):?>
                <div class="splide__slide">
                    <a href="destination_detail.html">
                    <div class="card card-style ms-3" style="background-image:url(<?= $post->cover->url ?? $this->asset('images/travel/1m.jpg');?>);" data-card-height="300">
                        <div class="card-top px-3 py-3">
                            <a href="#" data-menu="menu-heart" class="bg-white rounded-sm icon icon-xs float-end"><i class="fa fa-heart color-red-dark"></i></a>
                            <a href="<?= $this->router->to('sitePostSingle', ['slug' => $post->slug])?>" class="bg-white color-black rounded-sm btn btn-xs float-start font-700 font-12">Explore</a>
                        </div>
                        <div class="card-bottom px-3 py-3">
                            <h1 class="color-white"><?= $post->title->safe ?></h1>
                        </div>
                        <div class="card-overlay bg-gradient opacity-30"></div>
                        <div class="card-overlay bg-gradient"></div>
                    </div>
                    </a>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <div class="content mt-0 mb-n1">
        <div class="d-flex">
            <div class="align-self-center">
                <h1 class="mb-0 font-16">Fun Event</h1>
            </div>
            <div class="ms-auto align-self-center">
                <a href="<?= $this->router->to('sitePostList', ['type' => 'article '])?>" class="float-end font-12 font-400">See All</a>
            </div>
        </div>
    </div>

    <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-1">
        <div class="splide__track">
            <div class="splide__list">
                <?php foreach($articles as $post):?>
                <div class="splide__slide">
                    <a href="<?= $this->router->to('sitePostSingle', ['slug' => $post->slug])?>">
                    <div class="card m-2 mb-1 card-style">
                        <img src="<?= $post->cover->url ?? $this->asset('images/travel/3s.jpg');?>" class="img-fluid">
                        <div class="p-2 bg-theme rounded-sm">
                            <h4 class="font-17 pt-1 line-height-s pb-0 mb-n1"><?= $post->title->safe ?></h4>
                            <span class="font-10 mb-0">Free</span>
                        </div>
                    </div>
                    </a>
                </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <div class="content mb-n1">
        <div class="d-flex">
            <div class="align-self-center">
                <h1 class="mb-0 font-16">Special Tour Guide</h1>
            </div>
            <div class="ms-auto align-self-center">
                <a href="<?= $this->router->to('sitePostList', ['type' => 'tour-guide '])?>" class="float-end font-12 font-400">See All</a>
            </div>
        </div>
    </div>

    <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-3">
        <div class="splide__track">
            <div class="splide__list">
                
                <?php foreach($tour_guides as $post):?>
                    <div class="splide__slide">
                        <a href="<?= $this->router->to('sitePostSingle', ['slug' => $post->slug])?>">
                        <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $post->cover->url ?? $this->asset('images/travel/7m.jpg');?>)">
                            <div class="card-bottom mb-2">
                                <h5 class="color-white font-15 text-center pb-1"><?= $post->title->safe ?></h5>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <div class="content mb-0">
        <div class="d-flex">
            <div class="align-self-center">
                <h1 class="mb-0 font-18">Get Local Souvernirs</h1>
            </div>
            <div class="ms-auto align-self-center">
                <a href="<?= $this->router->to('siteProductList')?>" class="float-end font-12 font-400">Order Now</a>
            </div>
        </div>
    </div>	

    <div class="splide story-slider visible-slider slider-no-arrows slider-no-dots" id="tripple-slider-2">
        <div class="splide__track">
            <div class="splide__list">
                <?php foreach($products as $product):?>
                <div class="splide__slide">
                    <div class="card m-2 mb-1 card-style">
                        <img src="<?= $product->cover->url ?? $this->asset('images/pictures/17s.jpg');?>" class="img-fluid">
                        <div class="p-2 bg-theme rounded-sm">
                            <h4 class="font-17 pt-1 line-height-s pb-0 mb-n1"><?= $product->name->safe ?></h4>
                            <span class="font-10 mb-0">IDR <?= number_format($product->price->one) ?></span>
                        </div>
                    </div>
                    
                </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>

    <div class="content mb-n1">
        <div class="d-flex">
            <div class="align-self-center">
                <h1 class="mb-0 font-16">Curated Hotel</h1>
            </div>
            <div class="ms-auto align-self-center">
                <a href="<?= $this->router->to('sitePostList', ['type' => 'hotel '])?>" class="float-end font-12 font-400">See All</a>
            </div>
        </div>
    </div>

    <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-4">
        <div class="splide__track">
            <div class="splide__list">
                <?php foreach($hotels as $post):?>
                <div class="splide__slide">
                        <a href="<?= $this->router->to('sitePostSingle', ['slug' => $post->slug])?>">
                        <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?=  $post->cover->url ?? $this->asset('images/travel/7m.jpg');?>)">
                            <div class="card-bottom mb-2">
                                <h5 class="color-white font-15 text-center pb-1"><?= $post->title->safe ?></h5>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                    </a>
                </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>


</div>
<!-- Page content ends here-->