<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
<title>AppKit Mobile</title>
<link rel="stylesheet" type="text/css" href="<?= $this->asset('styles/bootstrap.css');?>">
<link rel="stylesheet" type="text/css" href="<?= $this->asset('styles/style.css');?>">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= $this->asset('fonts/css/fontawesome-all.min.css');?>">
<link rel="manifest" href="<?= $this->asset('_manifest.json');?>" data-pwa-version="set_in_manifest_and_pwa_js">
<link rel="apple-touch-icon" sizes="180x180" href="<?= $this->asset('app/icons/icon-192x192.png');?>">
</head>

<body class="theme-light">

<div id="preloader"><div class="spinner-border color-highlight" role="status"></div></div>

<div id="page">

    <div class="header header-fixed header-logo-center header-auto-show">
        <a href="index.html" class="header-title">Welcome</a>
        <a href="#" data-back-button class="header-icon header-icon-1"><i class="fas fa-chevron-left"></i></a>
        <a href="#" data-menu="menu-main" class="header-icon header-icon-4"><i class="fas fa-bars"></i></a>
        <a href="#" data-toggle-theme class="header-icon header-icon-3 show-on-theme-dark"><i class="fas fa-sun"></i></a>
        <a href="#" data-toggle-theme class="header-icon header-icon-3 show-on-theme-light"><i class="fas fa-moon"></i></a>
    </div>

    <div id="footer-bar" class="footer-bar-6">
        <a href="destination_list.html"><i class="fa fa-layer-group"></i><span>Destinasi</span></a>
        <a href="event_list.html" class="active-nav"><i class="fa fa-file"></i><span>Event</span></a>
        <a href="tour_guide_list.html" class=""><i class="fa fa-home"></i><span>Tour Guide</span></a>
        <a href="souvernir_list.html"><i class="fa fa-camera"></i><span>Souvernirs</span></a>
        <a href="hotel_list.html"><i class="fa fa-bars"></i><span>Hotel</span></a>
    </div>

    <div class="page-title page-title-fixed">
        <h1>Welcome</h1>
        <a href="#" class="page-title-icon shadow-xl bg-theme color-theme" data-menu="menu-share"><i class="fa fa-share-alt"></i></a>
        <a href="#" class="page-title-icon shadow-xl bg-theme color-theme show-on-theme-light" data-toggle-theme><i class="fa fa-moon"></i></a>
        <a href="#" class="page-title-icon shadow-xl bg-theme color-theme show-on-theme-dark" data-toggle-theme><i class="fa fa-lightbulb color-yellow-dark"></i></a>
        <a href="#" class="page-title-icon shadow-xl bg-theme color-theme" data-menu="menu-main"><i class="fa fa-bars"></i></a>
    </div>
    <div class="page-title-clear"></div>

    <div class="page-content mt-n1">

        <div class="content mt-n4 mb-4">
            <div class="search-box search-dark shadow-sm border-0 mt-4 bg-theme rounded-sm bottom-0">
                <i class="fa fa-search ms-1"></i>
                <input type="text" class="border-0" placeholder="Searching for something? Try 'dubai'" data-search>
            </div>
            <div class="search-results disabled-search-list">
                <div>
                    <a href="destination_detail.html" data-filter-item data-filter-name="all city night life dubai party neon ">
                        <div class="d-flex mt-4">
                            <div class="align-self-center">
                                <img src="<?= $this->asset('images/travel/1s.jpg');?>" class="rounded-m me-3" width="60">
                            </div>
                            <div class="align-self-center">
                                <h2 class="font-15 font-600 mb-0 line-height-s mt-1">City Nights <br> Dubai Destination </h2>
                            </div>
                            <div class="ms-auto ps-3 align-self-center text-center">
                                <span class="btn btn-xs gradient-blue text-uppercase font-600 rounded-s border-0">Book Now</span>
                            </div>
                        </div>
                    </a>
                    <a href="#" data-filter-item data-filter-name="all yoesemite park natural nature waterfall">
                        <div class="d-flex mt-4">
                            <div class="align-self-center">
                                <img src="<?= $this->asset('images/travel/6s.jpg');?>" class="rounded-m me-3" width="60">
                            </div>
                            <div class="align-self-center">
                                <h2 class="font-15 font-600 mb-0 line-height-s mt-1">Yosemite Natural <br>Park Expedition </h2>
                            </div>
                            <div class="ms-auto ps-3 align-self-center text-center">
                                <span class="btn btn-xs gradient-blue text-uppercase font-600 rounded-s border-0">Book Now</span>
                            </div>
                        </div>
                    </a>
                    <a href="#" data-filter-item data-filter-name="all bali nature beauty earth wonder hike">
                        <div class="d-flex mt-4">
                            <div class="align-self-center">
                                <img src="<?= $this->asset('images/travel/7s.jpg');?>" class="rounded-m me-3" width="60">
                            </div>
                            <div class="align-self-center">
                                <h2 class="font-15 font-600 mb-0 line-height-s mt-1">Bali's Natural<br>Wonders Hike </h2>
                            </div>
                            <div class="ms-auto ps-3 align-self-center text-center">
                                <span class="btn btn-xs gradient-blue text-uppercase font-600 rounded-s border-0">Book Now</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="search-no-results disabled mt-4">
            <div class="card card-style">
                <div class="content">
                    <h1>No Results</h1>
                    <p>
                        Your search brought up no results. Try using a different keyword. Or try typying all
                        to see all items in the demo. These can be linked to anything you want.
                    </p>
                </div>
            </div>
        </div>

        <div class="content mt-0 mb-n1">
            <div class="d-flex">
                <div class="align-self-center">
                    <h1 class="mb-0 font-16">Destination at xxx</h1>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="destination_list.html" class="float-end font-12 font-400">See All</a>
                </div>
            </div>
        </div>

        <div class="splide single-slider slider-no-arrows visible-slider slider-no-dots" id="single-slider-1">
            <div class="splide__track">
                <div class="splide__list">
                    <div class="splide__slide">
                        <a href="destination_detail.html">
                        <div class="card card-style ms-3" style="background-image:url(<?= $this->asset('images/travel/1m.jpg');?>);" data-card-height="300">
                            <div class="card-top px-3 py-3">
                                <a href="#" data-menu="menu-heart" class="bg-white rounded-sm icon icon-xs float-end"><i class="fa fa-heart color-red-dark"></i></a>
                                <a href="#" class="bg-white color-black rounded-sm btn btn-xs float-start font-700 font-12">Explore</a>
                            </div>
                            <div class="card-bottom px-3 py-3">
                                <h1 class="color-white">City Nights<br>Dubai Parties</h1>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="destination_detail.html">
                        <div class="card card-style ms-3" style="background-image:url(<?= $this->asset('images/travel/6m.jpg');?>);" data-card-height="300">
                            <div class="card-top px-3 py-3">
                                <a href="#" data-menu="menu-heart" class="bg-white rounded-sm icon icon-xs float-end"><i class="fa fa-heart color-red-dark"></i></a>
                                <a href="#" class="bg-white color-black rounded-sm btn btn-xs float-start font-700 font-12">Explore</a>
                            </div>
                            <div class="card-bottom px-3 py-3">
                                <h1 class="color-white">Yosemite Natural<br>Park Expedition</h1>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="destination_detail.html">
                        <div class="card card-style ms-3" style="background-image:url(<?= $this->asset('images/travel/7m.jpg');?>);" data-card-height="300">
                            <div class="card-top px-3 py-3">
                                <a href="#" data-menu="menu-heart" class="bg-white rounded-sm icon icon-xs float-end"><i class="fa fa-heart color-red-dark"></i></a>
                                <a href="#" class="bg-white color-black rounded-sm btn btn-xs float-start font-700 font-12">Explore</a>
                            </div>
                            <div class="card-bottom px-3 py-3">
                                <h1 class="color-white">Bali's Natural<br>Wonders Hike</h1>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-0 mb-n1">
            <div class="d-flex">
                <div class="align-self-center">
                    <h1 class="mb-0 font-16">Fun Event</h1>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="event_list.html" class="float-end font-12 font-400">See All</a>
                </div>
            </div>
        </div>

        <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-1">
            <div class="splide__track">
                <div class="splide__list">
                    <div class="splide__slide">
                        <a href="event_detail.html">
                        <div class="card m-2 mb-1 card-style">
                            <img src="<?= $this->asset('images/travel/3s.jpg');?>" class="img-fluid">
                            <div class="p-2 bg-theme rounded-sm">
                                <h4 class="font-17 pt-1 line-height-s pb-0 mb-n1">Jalan Sehat Bersama Walikota</h4>
                                <span class="font-10 mb-0">Free</span>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="event_detail.html">
                        <div class="card m-2 mb-1 card-style">
                            <img src="<?= $this->asset('images/travel/6s.jpg');?>" class="img-fluid">
                            <div class="p-2 bg-theme rounded-sm">
                                <h4 class="font-17 pt-1 line-height-s pb-0 mb-n1">Lari Pagi</h4>
                                <span class="font-10 mb-0">htm IDR 10.000</span>
                            </div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="event_detail.html">
                        <div class="card m-2 mb-1 card-style">
                            <img src="<?= $this->asset('images/travel/8s.jpg');?>" class="img-fluid">
                            <div class="p-2 bg-theme rounded-sm">
                                <h4 class="font-17 pt-1 line-height-s pb-0 mb-n1">Pertunjukan</h4>
                                <span class="font-10 mb-0">Free</span>
                            </div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mb-n1">
            <div class="d-flex">
                <div class="align-self-center">
                    <h1 class="mb-0 font-16">Special Tour Guide</h1>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="tour_guide_list.html" class="float-end font-12 font-400">See All</a>
                </div>
            </div>
        </div>

        <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-3">
            <div class="splide__track">
                <div class="splide__list">
                    <div class="splide__slide">
                        <a href="tour_guide_detail.html">
                        <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/7m.jpg');?>)">
                            <div class="card-bottom mb-2">
                                <h5 class="color-white font-15 text-center pb-1">Tour Guide 1</h5>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="tour_guide_detail.html">
                        <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/5m.jpg');?>)">
                            <div class="card-bottom mb-2">
                                <h5 class="color-white font-15 text-center pb-1">Tour Guide 2</h5>
                            </div>
                            <div class="card-overlay bg-gradien opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="tour_guide_detail.html">
                        <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/6m.jpg');?>)">
                            <div class="card-bottom mb-2">
                                <h5 class="color-white font-15 text-center pb-1">Tour Guide 3</h5>
                            </div>
                            <div class="card-overlay bg-gradient opacity-30"></div>
                            <div class="card-overlay bg-gradient"></div>
                        </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mb-n1">
            <div class="d-flex">
                <div class="align-self-center">
                    <h1 class="mb-0 font-16">Get Local Souvernirs</h1>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="souvernir_list.html" class="float-end font-12 font-400">See All</a>
                </div>
            </div>
            <div class="row mb-n4">
                <div class="col-6 pe-1">
                    <a href="souvernir_detail.html">
                    <div class="card card-style mx-0" style="background-image:url(<?= $this->asset('images/travel/1m.jpg');?>);" data-card-height="350">
                        <div class="card-bottom p-3">
                            <h2 class="color-white">Store 1</h2>
                            <p class="color-white opacity-60 line-height-s">
                                Experience a Night Life like never before.
                            </p>
                        </div>
                        <div class="card-overlay bg-gradient opacity-30"></div>
                        <div class="card-overlay bg-gradient"></div>
                    </div>
                </a>
                </div>
                <div class="col-6">
                    <a href="souvernir_detail.html">
                    <div class="card card-style mx-0 mb-2" style="background-image:url(<?= $this->asset('images/travel/8m.jpg');?>);" data-card-height="170">
                        <div class="card-bottom p-3">
                            <h2 class="color-white">Store 2</h2>
                            <p class="color-white opacity-60 line-height-s font-12">
                                Nature's beauty explored. Pure beauty.
                            </p>
                        </div>
                        <div class="card-overlay bg-gradient opacity-30"></div>
                        <div class="card-overlay bg-gradient"></div>
                    </div>
                    </a>
                    <a href="souvernir_detail.html">
                    <div class="card card-style mx-0 mb-0" style="background-image:url(<?= $this->asset('images/travel/5m.jpg');?>);" data-card-height="170">
                        <div class="card-bottom p-3">
                            <h2 class="color-white">Store 3</h2>
                            <p class="color-white opacity-60 line-height-s font-12">
                                A natura park and wonder of the world
                            </p>
                        </div>
                        <div class="card-overlay bg-gradient opacity-30"></div>
                        <div class="card-overlay bg-gradient"></div>
                    </div>
                </a>
                </div>
            </div>
        </div>

        <div class="content mb-n1">
            <div class="d-flex">
                <div class="align-self-center">
                    <h1 class="mb-0 font-16">Curated Hotel</h1>
                </div>
                <div class="ms-auto align-self-center">
                    <a href="hotel_list.html" class="float-end font-12 font-400">See All</a>
                </div>
            </div>
        </div>

        <div class="splide double-slider visible-slider slider-no-arrows slider-no-dots ps-2" id="double-slider-4">
            <div class="splide__track">
                <div class="splide__list">
                    <div class="splide__slide">
                        <a href="hotel_detail.html">
                            <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/7m.jpg');?>)">
                                <div class="card-bottom mb-2">
                                    <h5 class="color-white font-15 text-center pb-1">Yosemite Hotel</h5>
                                </div>
                                <div class="card-overlay bg-gradient opacity-30"></div>
                                <div class="card-overlay bg-gradient"></div>
                            </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="hotel_detail.html">
                            <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/5m.jpg');?>)">
                                <div class="card-bottom mb-2">
                                    <h5 class="color-white font-15 text-center pb-1">Bali Hotel</h5>
                                </div>
                                <div class="card-overlay bg-gradien opacity-30"></div>
                                <div class="card-overlay bg-gradient"></div>
                            </div>
                        </a>
                    </div>
                    <div class="splide__slide">
                        <a href="hotel_detail.html">
                            <div data-card-height="160" class="card rounded-m m-2 shadow-l" style="background-image:url(<?= $this->asset('images/travel/6m.jpg');?>)">
                                <div class="card-bottom mb-2">
                                    <h5 class="color-white font-15 text-center pb-1">Savana Hotel</h5>
                                </div>
                                <div class="card-overlay bg-gradient opacity-30"></div>
                                <div class="card-overlay bg-gradient"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>


        <div class="mt-4" data-menu-load="menu-footer.html"></div>
    </div>
    <!-- Page content ends here-->

    <!-- Added to Bookmarks Menu-->
    <div id="menu-heart"
         class="menu menu-box-modal rounded-m"
         data-menu-hide="1000"
         data-menu-width="250"
         data-menu-height="170">

        <h1 class="text-center mt-3 pt-2">
            <i class="fa fa-heart color-red-dark fa-3x scale-icon"></i>
        </h1>
        <h3 class="text-center pt-2">Saved to Favorites</h3>
    </div>

    <!-- Main Menu-->
    <div id="menu-main" class="menu menu-box-left rounded-0" data-menu-load="menu-main.html" data-menu-width="280" data-menu-active="nav-pages"></div>

    <!-- Share Menu-->
    <div id="menu-share" class="menu menu-box-bottom rounded-m" data-menu-load="menu-share.html" data-menu-height="370"></div>

    <!-- Colors Menu-->
    <div id="menu-colors" class="menu menu-box-bottom rounded-m" data-menu-load="menu-colors.html" data-menu-height="480"></div>


</div>

<script type="text/javascript" src="<?= $this->asset('scripts/bootstrap.min.js');?>"></script>
<script type="text/javascript" src="<?= $this->asset('scripts/custom.js');?>"></script>
</body>
