<!-- Added to Bookmarks Menu-->
<div id="menu-heart"
        class="menu menu-box-modal rounded-m"
        data-menu-hide="1000"
        data-menu-width="250"
        data-menu-height="170">

    <h1 class="text-center mt-3 pt-2">
        <i class="fa fa-heart color-red-dark fa-3x scale-icon"></i>
    </h1>
    <h3 class="text-center pt-2">Saved to Favorites</h3>
</div>

<!-- Main Menu-->
<div id="menu-main" class="menu menu-box-left rounded-0" data-menu-load="menu-main.html" data-menu-width="280" data-menu-active="nav-pages"></div>

<!-- Share Menu-->
<div id="menu-share" class="menu menu-box-bottom rounded-m" data-menu-load="menu-share.html" data-menu-height="370"></div>

<!-- Colors Menu-->
<div id="menu-colors" class="menu menu-box-bottom rounded-m" data-menu-load="menu-colors.html" data-menu-height="480"></div>
