<div id="footer-bar" class="footer-bar-6">
    <a href="<?= $this->router->to('sitePostList', ['type' => 'destination']) ?>" class="<?= $this->req->route->name == 'sitePostList' && $this->req->param->type == 'destination' ? 'active-nav':''?>"><i class="fa fa-layer-group"></i><span>Destinasi</span></a>
    <a href="<?= $this->router->to('sitePostList', ['type' => 'article']) ?>" class="<?= $this->req->route->name == 'sitePostList' && $this->req->param->type == 'article' ? 'active-nav':''?>"><i class="fa fa-file"></i><span>Event</span></a>
    <a href="<?= $this->router->to('sitePostList', ['type' => 'tour-guide']) ?>" class="<?= $this->req->route->name == 'sitePostList' && $this->req->param->type == 'tour-guide' ? 'active-nav':''?>"><i class="fa fa-home"></i><span>Tour Guide</span></a>
    <a href="souvernir_list.html" class="<?= $this->req->route->name == 'sitePostList' && $this->req->param->type == 'souvernir' ? 'active-nav':''?>"><i class="fa fa-camera"></i><span>Souvernirs</span></a>
    <a href="<?= $this->router->to('sitePostList', ['type' => 'hotel']) ?>" class="<?= $this->req->route->name == 'sitePostList' && $this->req->param->type == 'hotel' ? 'active-nav':''?>"><i class="fa fa-bars"></i><span>Hotel</span></a>
</div>
