<?php
/* GENERATE BY CLI */
/* DON'T MODIFY */

return [
    'core' => 'https://github.com/getmim/core.git',
    'admin-post' => 'https://github.com/getmim/admin-post.git',
    'admin' => 'https://github.com/getmim/admin.git',
    'admin-ui' => 'https://github.com/getmim/admin-ui.git',
    'lib-user' => 'https://github.com/getmim/lib-user.git',
    'lib-enum' => 'https://github.com/getmim/lib-enum.git',
    'lib-formatter' => 'https://github.com/getmim/lib-formatter.git',
    'lib-user-main' => 'https://github.com/getmim/lib-user-main.git',
    'lib-model' => 'https://github.com/getmim/lib-model.git',
    'cli' => 'https://github.com/getmim/cli.git',
    'lib-model-mysql' => 'https://github.com/getmim/lib-model-mysql.git',
    'lib-user-auth-cookie' => 'https://github.com/getmim/lib-user-auth-cookie.git',
    'lib-view' => 'https://github.com/getmim/lib-view.git',
    'lib-form' => 'https://github.com/getmim/lib-form.git',
    'lib-validator' => 'https://github.com/getmim/lib-validator.git',
    'lib-locale' => 'https://github.com/getmim/lib-locale.git',
    'lib-cache' => 'https://github.com/getmim/lib-cache.git',
    'lib-user-perm' => 'https://github.com/getmim/lib-user-perm.git',
    'post' => 'https://github.com/getmim/post.git',
    'lib-pagination' => 'https://github.com/getmim/lib-pagination.git',
    'lib-upload' => 'https://github.com/getmim/lib-upload.git',
    'api' => 'https://github.com/getmim/api.git',
    'lib-media' => 'https://github.com/getmim/lib-media.git',
    'lib-image' => 'https://github.com/getmim/lib-image.git',
    'lib-compress' => 'https://github.com/getmim/lib-compress.git',
    'admin-site-meta' => 'https://github.com/getmim/admin-site-meta.git',
    'site-meta' => 'https://github.com/getmim/site-meta.git',
    'site' => 'https://github.com/getmim/site.git',
    'lib-cache-output' => 'https://github.com/getmim/lib-cache-output.git',
    'site-setting' => 'https://github.com/getmim/site-setting.git',
    'lib-robot' => 'https://github.com/getmim/lib-robot.git',
    'api-post' => 'https://github.com/getmim/api-post.git',
    'lib-app' => 'https://github.com/getmim/lib-app.git',
    'admin-post-category' => 'https://github.com/getmim/admin-post-category.git',
    'post-category' => 'https://github.com/getmim/post-category.git',
    'post-category-logo' => 'https://github.com/getmim/post-category-logo.git',
    'api-post-category' => 'https://github.com/getmim/api-post-category.git',
    'api-static-page' => 'https://github.com/getmim/api-static-page.git',
    'static-page' => 'https://github.com/getmim/static-page.git',
    'admin-static-page' => 'https://github.com/getmim/admin-static-page.git',
    'cli-app-model' => 'https://github.com/getmim/cli-app-model.git',
    'cli-app' => 'https://github.com/getmim/cli-app.git'
];