<?php
    $title = $this->config->name;
    if(isset($_meta['title']))
        $title = $_meta['title'] ;
?>

<div class="header header-fixed header-logo-center header-auto-show">
        <a href="#" class="header-title"><?= $_meta['title'] ?></a>
        <!-- <a href="#" data-menu="menu-main" class="header-icon header-icon-4"><i class="fas fa-bars"></i></a> -->
        <!-- <a href="#" data-toggle-theme class="header-icon header-icon-3 show-on-theme-dark"><i class="fas fa-sun"></i></a> -->
        <!-- <a href="#" data-toggle-theme class="header-icon header-icon-3 show-on-theme-light"><i class="fas fa-moon"></i></a> -->
    </div>
    
<div class="page-title page-title-fixed">
    <h1><?= $title ?></h1>
</div>
<div class="page-title-clear"></div>

<div class="page-content">
        <div class="content mt-0 mb-0">

            <?php if(empty($posts)): ?>
                <p class=" card rounded p-2 text-center">There is no post yet </>
            <?php else: ?>
                <div class="row">
            <?php foreach($posts as $post): ?>
                <div class="col-12">
                    <div class="card card-style">
                        <a href="<?= $this->router->to('sitePostSingle', ['slug' => $post->slug ])?>">
                            <div style="background-image:url(<?= $post->cover->url ?? $this->asset('images/travel/1m.jpg');?>); height: 300px;background-position: center;background-size: cover;background-repeat: no-repeat;" ></div>
                            <div class="p-2 bg-theme rounded-sm">
                                <div class="d-flex">
                                    <div>
                                        <h4 class=""><?= $post->title->safe ?></h4>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach;?>
            </div>
            <?php endif;?>
            
        </div>

    </div>
    <!-- Page content ends here-->