<div class="page-content">

        <div class="card rounded-0" style="background-image: url(<?= $post->cover->url ?>);" data-card-height="450">
            <div class="card-top mt-3 pb-5 ps-3">
                <a href="#" data-back-button class="icon icon-s bg-theme rounded-xl float-start me-3"><i class="fa color-theme fa-arrow-left"></i></a>
            </div>
            <div class="card-overlay bg-gradient"></div>
        </div>
        
        <!-- margin top and margin bottom negative values repesent how much you want the article to go over the above and below image-->
        <div class="card card-style" style="margin-top:-100px;z-index:1">
            <div class="content">
                <p class="mb-n1 color-highlight font-600"><?= implode(', ', $post->category)?></p>
                <h1>
                    <?= $post->title->safe ?>
                </h1>
                
                <?= $post->content ?>
            </div>
        </div>

        <?php if($post->type != 2 ):?>
        <div class="card card-style">
			<div class="content">
				<h5>Location</h4>
                <p class="mb-1"><?= $post->info->address ?? ''  ?></p>
                <?php if(!empty($post->info->price)) :?>
                <h5>Price</h4>
                <p>Start From IDR <?= number_format($post->info->price)  ?></p>
                <?php endif;?>
                <?php if(!empty($post->info->url)) :?>
				<a href="<?=$post->info->url ?>" class="default-link btn btn-m rounded-sm font-700 text-uppercase btn-full gradient-green border-0"><?= $post->type == 3 ? 'Book Now':'Location'?></a>
                <?php endif;?>
			</div>
		</div>
        <?php endif;?>
        
    </div>
    <!-- Page content ends here-->