<div class="page-content">

        <div class="card rounded-0" style="background-image: url(<?= $post->cover->url ?>);" data-card-height="450">
            <div class="card-top mt-3 pb-5 ps-3">
                <a href="#" data-back-button class="icon icon-s bg-theme rounded-xl float-start me-3"><i class="fa color-theme fa-arrow-left"></i></a>
                <a href="#" data-menu="menu-share"  class="icon icon-s bg-theme rounded-xl float-end me-3"><i class="fa color-theme fa-share-alt"></i></a>
            </div>
            <div class="card-overlay bg-gradient"></div>
        </div>
        
        <!-- margin top and margin bottom negative values repesent how much you want the article to go over the above and below image-->
        <div class="card card-style" style="margin-top:-100px;z-index:1">
            <div class="content">
                <p class="mb-n1 color-highlight font-600"><?= implode(', ', $post->category)?></p>
                <h1>
                    <?= $post->title->safe ?>
                </h1>
                
                <?= $post->content ?>
                

                <div class="divider"></div>
                
                <div class="d-flex">
                    <div class="me-2">
                        <img src="<?= $post->user->avatar ?>" width="40" class="rounded-s">
                    </div>
                    <div>
                        <h5><?= $post->user->fullname ?></h5>
                    </div>
                    <div class="ms-auto">
                        <a href="#" data-menu="menu-share" class="icon icon-s bg-theme shadow-xl rounded-xl float-end"><i class="fa color-theme fa-share-alt"></i></a>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
    <!-- Page content ends here-->