<form  method="POST" class="needs-validation main" novalidate>
    <nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
        <div class="navbar-multiline mr-auto">
            <span class="navbar-brand" href="#0"><?= $type_text ?> Editor</span>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                    <li class="breadcrumb-item"><a href="<?= $this->router->to('adminPost', ['type' => $this->req->param->type]) ?>"><?= $type_text ?></a></li>
                    <li class="breadcrumb-item active" aria-current="page"><?= $subtitle ?></li>
                </ol>
            </nav>
        </div>
        <button class="btn btn-primary">Save</button>
    </nav>

    <div class="container p-3">
        <div class="row mb-3">
            <?= $form->csrfField('noob') ?>
            <input type="hidden" name="type" value="<?= $type ?>">
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $form->field('title'); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $form->field('slug'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?= $form->field('content'); ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <?= $form->field('cover-url'); ?>
                                <?= $form->field('cover-label'); ?>
                                <?php if(module_exists('admin-post-website')): ?>
                                    <?= $form->field('website', $opts['website']); ?>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-4">
                                <?= $form->field('embed'); ?>
                                <?php if(module_exists('admin-post-gallery')): ?>
                                    <?= $form->field('gallery', $opts['gallery']); ?>
                                <?php endif; ?>
                                <?php if(module_exists('admin-post-plagiarism')): ?>
                                    <?php if($this->can_i->plagiarism_post): ?>
                                        <?= $form->field('plagiarism'); ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-4">
                                <?php if(module_exists('admin-post-category')): ?>
                                    <?= $form->field('category', $opts['category']); ?>
                                <?php endif; ?>
                                <?= $form->field('status', $statuses) ?>
                            </div>
                        </div>
                    </div>
                </div>
                            <?php if(!in_array($type, [2])):?>
                <div class="card mt-3">
                    <div class="card-header">Detail Information</div>
                    <div class="card-body">
                        <div class="row">
                            
                            <?php if(!in_array($type, [4])):?>
                            <div class="col-md-12">
                                <?= $form->field('info-address'); ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field('info-url'); ?>
                            </div>
                            <?php endif; ?>
                            <?php if(in_array($type, [3,4])):?>
                            <div class="col-md-12">
                                <?= $form->field('info-price', null, ($type == 4 ? 'Price per Person':'')); ?>
                            </div>
                            <div class="col-md-12">
                                <?= $form->field('info-phone'); ?>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                            <?php endif; ?>
            </div>
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <?= $this->partial('site-meta/meta'); ?>
                        <?php if($this->can_i->feature_post): ?>
                            <?= $form->field('featured'); ?>
                        <?php endif; ?>
                        <?php if($this->can_i->editor_pick_post): ?>
                        <?= $form->field('editor_pick'); ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
