
<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0"><?= $contact->type ?> Reservation Details</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminContact') ?>"><?= $contact->type ?> Reservation</a></li>
                <li class="breadcrumb-item active" aria-current="page">Details</li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><?= $contact->fullname ?> - <?= $contact->post->title ?></h5>
                    <div>
                        <table>
                            <tr>
                                <td>Name</td>
                                <td>: <?= $contact->fullname->safe ?></td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>: <?= $contact->email ?></td>
                            </tr>
                            <tr>
                                <td>Phone</td>
                                <td>: <?= $contact->phone ?></td>
                            </tr>
                            <tr>
                                <td>People</td>
                                <td>: <?= $contact->amount ?></td>
                            </tr>
                            <tr>
                                <td>Activity</td>
                                <td>: <?= $contact->post->title ?></td>
                            </tr>
                            <tr>
                                <td>Event Date</td>
                                <td>: <?= $contact->date->format('M d, Y H:i') ?></td>
                            </tr>
                            <tr>
                                <td>Reserved at</td>
                                <td>: <?= $contact->created->format('M d, Y H:i') ?></td>
                            </tr>
                        </table>
                    </div>
                    <hr>
                    <div class="card-text">
                        Note: <br>
                        <?= nl2br($contact->description->safe) ?></div>
                </div>
            </div>
        </div>
    </div>
</div>