<!DOCTYPE html>
<html>
<head>
    <?= $this->partial('shared/head', ['_meta'=>$_meta]) ?>
</head>
<body class="theme-light">
    <div id="preloader"><div class="spinner-border color-highlight" role="status"></div></div>
    <div class="page" id="page">
        <?= $this->partial('shared/header') ?>
        <?= $content ?>
        <?= $this->partial('shared/footer') ?>

         <!-- Install Prompt for Android -->
    <div id="menu-install-pwa-android" class="menu menu-box-bottom rounded-m"
        data-menu-height="380" 
        data-menu-effect="menu-parallax">
        <img class="mx-auto mt-4 rounded-m" src="<?= $this->asset('favicon_io/192x192.png') ?>" alt="img" width="90">
        <h4 class="text-center mt-4 mb-2">Pasang Aplikasi Kelola Wisata</h4> 
        <p class="text-center boxed-text-xl">
            Tekan tombol Pasang Sekarang aplikasi akan langsung tersedia di Handphone Anda
        </p>
        <div class="boxed-text-l">
            <a href="#" class="pwa-install mx-auto btn btn-m font-600 bg-highlight">Pasang Sekarang</a>
            <a href="#" class="pwa-dismiss close-menu btn-full mt-3 pt-2 text-center text-uppercase font-600 color-red-light font-12">Lain Kali</a>
        </div>
    </div> 
    </div>
    
    <?= $this->partial('shared/foot', ['_meta'=>$_meta]) ?>
</body>
</html>